config/routes.rb
Rails.application.routes.draw do  

  post 'watching_statuses/select'

  get 'entries/index'

  get 'entries/show'

  get '/.well-known/acme-challenge/:id' => 'pages#certbot'

  resources :impressions do
    resources :comments, only: [:create, :destroy]
  end

  resources :likes, only: [:create, :destroy]
  resources :impressions,:episodes
  resources :relationships, only: [:create, :destroy]
  resources :casts, only: [:index, :show]
  resources :articles
  resources :posts

  get 'pages/privacy_policy'
  get 'episodes/show'

  get 'seasons/show'
  resources :feeds do
    member do
     resources :entries, only: [:index, :show]
   end
 end


 root :to => 'pages#index'

 devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => 'registrations' }

 resources :users do
  member do
    get :following, :followers
  end
end

resources :dramas do
  resources :seasons, shallow: true
end

get 'manage-impression/:id/basics' => 'impressions#basics', as: 'manage_impression_basics'
end

app/models/drama.rb
class Drama < ApplicationRecord
  # drama.seasonsのように取得できるようになる
  has_many :seasons
  has_many :drama_cast_relations
  has_many :casts, through: :drama_cast_relations
  has_many :watching_statuses, dependent: :destroy

end

app/controllers/dramas_controller.rb
require 'amazon/ecs'
require 'amazon-api'
class DramasController < ApplicationController
  PER = 7
  # 同じ処理をactionの前で行いたい場合、こんな風に描ける
  # before_action :hogehoge, only: [:index,:show]
  def index
    unless (params[:category]).nil? then
      @title = "海外ドラマ：#{getCategoryName}"
      @dramas = Drama.where(category: params[:category])
    else  
      @title = "話題のドラマ"
      @dramas = Drama.all
    end
    if request.from_smartphone? then
      @dramas.each do |drama|
        image = drama.image_url
        drama.image_url=image.to_s.sub!('300', '200')
      end
    end
    @subTitle = getSubTitle
  end

  def show
    @drama = Drama.find(params[:id])
    @drama.image_url=@drama.image_url.sub!('300', '100') if request.from_smartphone?
    @impressions = Impression.where(drama_id: @drama.id, impression_type: "0").order(:created_at).reverse_order.page(params[:page]).per(PER)
    @dramas = Drama.all
    @casts = @drama.casts
    @entryCategories = EntryCategory.where(name:@drama.title)
    @entries = Array.new
    @entryCategories.each do |entryCategory|
        @entries.push(entryCategory.entry)
    end
    @watchingStatus
    @watchingStatus = @drama.watching_statuses.where(user_id: current_user.id, drama_id: @drama.id) if user_signed_in?
    @status = 1 #ステータスを選択してください（デフォルト）
    @status = @watchingStatus.first.status unless @watchingStatus.blank?
  end

  private
  def getCategoryName
    if params[:category] == "0" then
      return "アクション"
    elsif params[:category] == "1" then
      return "ファンタジー"
    elsif params[:category] == "2" then
      return "ドラマ"
    elsif params[:category] == "3" then
      return "サスペンス・ミステリー"
    elsif params[:category] == "4" then
      return "ラブロマンス"
    elsif params[:category] == "5" then
      return "韓流"
    else
      return "話題のドラマ"
    end
  end
  def getSubTitle
    if params[:category] == "0" then
      return "海外ドラマといえばド派手なアクション！"
    elsif params[:category] == "1" then
      return "壮大な世界観で描かれるファンタジーの世界へ"
    elsif params[:category] == "2" then
      return "人間の出会い・別れの中で繰り広げられるストーリーに酔いしれる"
    elsif params[:category] == "3" then
      return "様々なストーリーに没頭"
    elsif params[:category] == "4" then
      return "恋がしたくなるような恋愛ドラマを見つけましょう"
    elsif params[:category] == "5" then
      return "話題の韓流ドラマをピックアップ"
    else
      return "mitano編集長がオススメする今話題のドラマです"
    end
  end
end

app/helpers/dramas_helper.rb
module DramasHelper
end

app/views/dramas/index.html.erb
<% set_meta_tags title: @title + " - 感想・レビュー・評価・あらすじ ", description: @subTitle, keywords: "話題の海外ドラマ,海外ドラマ,感想,評価",og: { title: @title, type: 'article'} %>

 <%= render "partial/navbar" %>

 <section id="portfolio" class="bg-light-gray row-space-top-4 row-space-4">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-sm-12 col-xs-12 text-center">
        <h3 class="matome-midasi"><%= @title %></h3>
        <h4 class="page-header"><%= @subTitle %></h4>
      </div>
    </div>

    <div class="row">
      <% @dramas.each do |drama|%>
      <% if drama.id != 0 %>
      <div class="col-md-4 col-sm-6 col-xs-6 portfolio-item  text-center">
        <span style="vertical-align:middle;">
          <%= link_to image_tag("#{drama.image_url}"), drama_path(drama)  %>
        </span>
        <div class="text-info .bg-info">
          <% if request.from_smartphone? %>
            <%= link_to truncate(drama.title, length: 12), drama_path(drama) %>
          <% else %>
            <%= link_to drama.title, drama_path(drama) %>
          <% end %>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/dramas/show.html.erb
<% set_meta_tags title: @drama.title+" - 感想・レビュー・評価・あらすじ", description: "#{@drama.title}の感想、レビュー。#{@drama.over_view}", keywords: "#{@drama.title},#{@drama.title}感想,感想,評価,海外ドラマ",og: { title: @drama.title, type: 'article', image: @drama.image_url } %>

<%= render "partial/navbar" %>
<section id="drama-show" class="bg-light-gray row-space-top-4 ">
 <div class="container">
  <% drama= @drama%>
  <%= render "partial/seasonTab", drama: drama, title: drama.title %>
  <%= link_to "HOME", root_path %> >
  <%= link_to "アクション", dramas_path(category: drama.category) %> >
  <%=link_to "#{drama.title}", drama_path(drama) %>
  <div class="episode-overview col-md-12 col-xs-12">
    <div class="col-md-4 col-sm-4 portfolio-item box1 row-space-2 center-block text-center">
      <span style="vertical-align:middle;">
        <%= image_tag("#{drama.image_url}",:align => 'center') %>
        <%= link_to image_tag("share_drama"),
        new_impression_path(impression_type: '0', drama_id: @drama.id) %> 
      </span>
    </div>
    <div class="col-md-8 col-sm-8 portfolio-item">
      <h4 class="episode-title"><%= @drama.title %></h4>
      <div class="row">
        <div class="col-md-12 col-sm-12">
          <p class="episode-summary"><%= @drama.over_view %></p>
          <div class="episode-summary row-space-1">
            <%= link_to "出典：#{drama.source_url}", drama.source_url %>
          </div>
          <div class="episode-summary row-space-1">
            出演：
            <% @casts.each do |cast| %>
            <%=link_to(cast.name,cast_path(cast))%>
            <% end %>
          </div>
          <div class="row">
           <div class="col-md-1 col-xs-3">
            <%= social_share_button_tag(drama.title+"の感想をmitanoで話し合おう！") %>         
          </div>
          <div class="col-sm-11 col-xs-9 row-space-1 selector_obj">
            <%= form_tag(watching_statuses_select_path,remote: true) do %>
            <select class="form-control select" name="watchingStatus" onchange="submit(this.form)">
              <option value="1 selected="<%='selecte' if @status == 1%>">ステータスを選択</option>
              <option value="2" <%= "selected=selected" if @status == 2%>">みてる</option>
              <option value="3" <%= "selected=selected" if @status == 3%>">みた</option>
              <option value="4" <%= "selected=selected" if @status == 4%>">みたい</option>
            </select>
            <%= hidden_field_tag :drama_id, @drama.id %>
            <% end %>          
          </div>
        </div>

      </div>

    </div>
  </div>
</div>  
</div>
</section>
<div class="row-space-1"></div>
<%= render 'partial/impressionArea', subtitle: 'このドラマに'  %>

app/views/dramas/show.js.erb
$('#loadpage').append("<%= escape_javascript(render 'impressions/impression',{impressions:@impressions}) %>")
$("#more_link").replaceWith("<%= escape_javascript(link_to_next_page(@impressions, 'もっと見る', remote: true, id: 'more_link')) %>");