config/routes.rb
Rails.application.routes.draw do  

  post 'watching_statuses/select'

  get 'entries/index'

  get 'entries/show'

  get '/.well-known/acme-challenge/:id' => 'pages#certbot'

  resources :impressions do
    resources :comments, only: [:create, :destroy]
  end

  resources :likes, only: [:create, :destroy]
  resources :impressions,:episodes
  resources :relationships, only: [:create, :destroy]
  resources :casts, only: [:index, :show]
  resources :articles
  resources :posts

  get 'pages/privacy_policy'
  get 'episodes/show'

  get 'seasons/show'
  resources :feeds do
    member do
     resources :entries, only: [:index, :show]
   end
 end


 root :to => 'pages#index'

 devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => 'registrations' }

 resources :users do
  member do
    get :following, :followers
  end
end

resources :dramas do
  resources :seasons, shallow: true
end

get 'manage-impression/:id/basics' => 'impressions#basics', as: 'manage_impression_basics'
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :drama, counter_cache: true
  has_many :episodes
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  PER = 7

  def show
    @season = Season.order(:id).find(params[:id])
    @drama = Drama.find(@season.drama_id)
    @drama.image_url=@drama.image_url.sub!('300', '100') if request.from_smartphone?
    @episodes =@season.episodes.order(:id)
    @impressions = Impression.where(season_id: @season.id, impression_type: "1").order(:created_at).reverse_order.page(params[:page]).per(PER)
    @dramas = Drama.order(created_at: 'desc')
    @entryCategories = EntryCategory.where(name:@drama.title)
    @entries = Array.new
    @entryCategories.each do |entryCategory|
        @entries.push(entryCategory.entry)
    end
  end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/show.html.erb
<% set_meta_tags title: @drama.title+@season.title+" - 感想・レビュー・評価・あらすじ ", description: "#{@drama.title}の感想、レビュー。#{@season.over_view}", keywords: "#{@drama.title}#{@season.title},海外ドラマ,感想,評価",og: { title: @drama.title, type: 'article', image: @drama.image_url } %>

<%= render "partial/navbar" %>
<section id="season-show" class="bg-light-gray row-space-top-4 row-space-4">
 <div class="container">
  <section id="episode-show" class="bg-light-gray row-space-top-4 row-space-4">
    <% drama= @drama%>
    <%= render "partial/seasonTab", drama: drama,title: drama.title+@season.title %>
    <%= link_to "HOME", root_path %> >
    <%= link_to "アクション", dramas_path(category: drama.category) %> >
    <%=link_to "#{drama.title}", drama_path(drama) %> >
    <%=link_to "#{@season.title}", season_path(@season) %>
    <div class="episode-overview col-md-12 ">
      <div class="col-md-4 col-sm-4 portfolio-item box1 row-space-2 center-block text-center">
        <span style="vertical-align:middle;" c>
          <%= image_tag("#{drama.image_url}",:align => 'center') %>
          <%= link_to image_tag("share_season"),
          new_impression_path(impression_type: '1', season_id: @season.id) %>
        </span>
      </div>
      <div class="col-md-8 col-sm-8 portfolio-item">
        <h4 class="episode-title"><%= drama.title+@season.title %></h4>
        <div class="row">
          <div class="col-md-12 col-sm-12">
            <p class="episode-summary"><%= @season.over_view %></p>
            <div class="episode-summary row-space-1">
              <%= link_to "出典: #{@season.source_url}", @season.source_url %>
            </div>
            <div>
              <%= social_share_button_tag(drama.title+"の感想をmitanoで話し合おう！") %>         
            </div>
          </div>

        </div>
      </div>
    </div>  
  </section>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">話数</th>
        <th scope="col">タイトル</th>
        <th scope="col">感想シェア数</th>
        <th scope="col">この話の感想をシェアする</th>
      </tr>
    </thead>
    <tbody>
      <% @count=0 %>
      <% @episodes.each do |episode| %>
      <tr>
        <th scope="row"><%= @count += 1 %></th>
        <td><%= link_to "#{episode.episode_name}",episode_path(episode) %></td>
        <td><%= episode.impressions.count %></td>
        <td><%= link_to image_tag("share"),
        new_impression_path(impression_type: '2', episode_id: episode.id) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</section>

<%= render 'partial/impressionArea', subtitle: 'このシーズンに'  %>

app/views/seasons/show.js.erb
$('#loadpage').append("<%= escape_javascript(render 'impressions/impression',{impressions:@impressions}) %>")
$("#more_link").replaceWith("<%= escape_javascript(link_to_next_page(@impressions, 'もっと見る', remote: true, id: 'more_link')) %>");