config/routes.rb
Rails.application.routes.draw do  

  post 'watching_statuses/select'

  get 'entries/index'

  get 'entries/show'

  get '/.well-known/acme-challenge/:id' => 'pages#certbot'

  resources :impressions do
    resources :comments, only: [:create, :destroy]
  end

  resources :likes, only: [:create, :destroy]
  resources :impressions,:episodes
  resources :relationships, only: [:create, :destroy]
  resources :casts, only: [:index, :show]
  resources :articles
  resources :posts

  get 'pages/privacy_policy'
  get 'episodes/show'

  get 'seasons/show'
  resources :feeds do
    member do
     resources :entries, only: [:index, :show]
   end
 end


 root :to => 'pages#index'

 devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => 'registrations' }

 resources :users do
  member do
    get :following, :followers
  end
end

resources :dramas do
  resources :seasons, shallow: true
end

get 'manage-impression/:id/basics' => 'impressions#basics', as: 'manage_impression_basics'
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_contents, dependent: :destroy
  # validates :title, presence: true
  # validates :image, presence: true
  # validates :heading, presence: true
  # validates :trailer, presence: true

end

app/models/cast.rb
class Cast < ApplicationRecord
  has_many :drama_cast_relations
  has_many :dramas, through: :drama_cast_relations
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :impression
  counter_culture :impression
  validates :content, presence: true
  validates :user_id, presence: true
  validates :impression_id, presence: true
end

app/models/drama.rb
class Drama < ApplicationRecord
  # drama.seasonsのように取得できるようになる
  has_many :seasons
  has_many :drama_cast_relations
  has_many :casts, through: :drama_cast_relations
  has_many :watching_statuses, dependent: :destroy

end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :feed
  has_many :entry_categories, dependent: :destroy
end

app/models/entry_category.rb
class EntryCategory < ApplicationRecord
  belongs_to :entry
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :season, counter_cache: true
  has_many :impressions
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :entries, dependent: :destroy
end

app/models/impression.rb
class Impression < ApplicationRecord
  belongs_to :user
  belongs_to :drama
  belongs_to :season
  belongs_to :episode
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy

  validates :impression, presence: true

  def add_like(user)
    likes.create(user_id: user.id)  
  end

  def delete_like(user)
    likes.find_by(user_id: user.id).destroy
  end

  def like?(user)
    like_users.include?(user)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :impression
  counter_culture :impression
  validates :user_id, presence: true
  validates :impression_id, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :drama, counter_cache: true
  has_many :episodes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook, :twitter]

  has_many :impressions, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :watching_statuses, dependent: :destroy

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.email= "#{auth.uid}-#{auth.provider}@example.com" if user.email.nil?
      user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    if auth.provider "twitter" then
      user.image= auth.info.image.gsub('normal', 'bigger')
    else
      user.image = "https://graph.facebook.com/#{auth.uid}/picture?type=large" # assuming the user model has an image
    end
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
  end

end
end

app/controllers/amazon-api.rb
# #! /usr/bin/ruby
# # coding: UTF-8

# require 'rubygems'
# require 'amazon/ecs'

# #  Amazon::Ecs.debug = true

# Amazon::Ecs.options = {
#   :associate_tag => "takanori501-22",
#     :AWS_access_key_id => "AKIAI5NY2QDECRNXCTXQ",
#     :AWS_secret_key => "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"
# }

# # res = Amazon::Ecs.item_search('ゲームオブスローンズ ', {:item_id => 'B07CGZ3YNP', :response_group => 'Medium,ItemAttributes,Images', :country => 'jp'})
#   # res = ::Amazon::Ecs.item_lookup("B07CGZ3YNP", country: 'jp', response_group: 'Large,ItemAttributes,Images')
#   # ウォーキング・デッド
#    # res = ::Amazon::Ecs.item_lookup("B07659TGS5", country: 'jp', response_group: 'Large,ItemAttributes,Images')
#   # 24
#   # res = ::Amazon::Ecs.item_lookup("B01A1BY4HC", country: 'jp', response_group: 'Large,ItemAttributes,Images')
#   # ゴシップガール
#   # res = ::Amazon::Ecs.item_lookup("B002M3UEOA", country: 'jp', response_group: 'Large,ItemAttributes,Images')
#   # シカゴ・ファイア
#   # res = ::Amazon::Ecs.item_lookup("B07CH52Y94", country: 'jp', response_group: 'Large,ItemAttributes,Images')
#   # マジシャンズ
#   # res = ::Amazon::Ecs.item_lookup("B079TN5PR8", country: 'jp', response_group: 'Large,ItemAttributes,Images')
#   # グリム
#   # res = ::Amazon::Ecs.item_lookup("B07261KV5B", country: 'jp', response_group: 'Large,ItemAttributes,Images')
#   # ブレイキング・バッド
#   # res = ::Amazon::Ecs.item_lookup("B00KYIN73K", country: 'jp', response_group: 'Large,ItemAttributes,Images')
#   # ザ・フォロイング
#   # res = ::Amazon::Ecs.item_lookup("B00R705PD8", country: 'jp', response_group: 'Large,ItemAttributes,Images')
#   # パーソン・オブ・インタレスト
#   # res = ::Amazon::Ecs.item_lookup("B00MM06OII", country: 'jp', response_group: 'Large,ItemAttributes,Images')
#   # トゥルー・ブラッド 
#   # res = ::Amazon::Ecs.item_lookup("B006FPU7CU", country: 'jp', response_group: 'Large,ItemAttributes,Images')
#   # DALLAS/ダラス スキャンダラス・シティ 
#   res = ::Amazon::Ecs.item_lookup("B013UO2N0M", country: 'jp', response_group: 'Large,ItemAttributes,Images')


# res.items.each do |item|

#   puts item.get_element('ItemAttributes')

#   #階層が下のものも取得できる
#   puts "Title:#{item.get('ItemAttributes/Title')}"
#   puts "Author:#{item.get('ItemAttributes/Author')}"

#   # 画像のurlとサイズをhashで取得
#   puts item.get_hash('SmallImage')
# end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order('updated_at desc')
  end

  def show
    @article = Article.find(params[:id])
    @articleContents = ArticleContent.where(article_id: @article.id)
    @articles = Article.all.order('updated_at desc')
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/casts_helper.rb
module CastsHelper
end

app/helpers/dramas_helper.rb
module DramasHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/articles/index.html.erb
<% set_meta_tags title: "「海外ドラマまとめ」の記事一覧", description: "海外ドラマのニュースや作品情報、レビュー、キャスト情報、視聴率、ランキングなどを掲載している海外ドラマサイト。", keywords: "話題の海外ドラマ,海外ドラマ,感想,評価",og: { title: "「海外ドラマまとめ」の記事一覧", type: 'article'} %>

<%= render "partial/navbar" %>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="row-space-3 episode-title drama-title3">2018年面白い話題の海外ドラマまとめ
      </h1>
    </div>    <div class="col-md-8">
      <% @articles.each do |article| %>

      <!-- Blog Post -->
      <div class="card mb-4 box1">
        <% if request.from_smartphone? %>
          <%= link_to image_tag(article.image,:class =>"sp-image"),article_path(article) %>
        <% else %>
          <%= link_to image_tag(article.image,:size =>"720x300"),article_path(article) %>
        <% end %>
        <div class="card-body">
          <h2 class="card-title"><%=link_to(article.title,article_path(article))%></h2>
          <p class="card-text"><%=article.heading%></p>
          <%= link_to "続きを読む", article_path(article)%>  
        </div>
        <div class="card-footer">
          更新：<%=article.updated_at.strftime("%Y年%m月%d日%H時%M分") %>by
          <%= link_to "佐藤夏菜子(mitano編集部)",user_path(10) %>
        </div>
      </div>
      <% end %>
    </div>
    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Categories Widget -->
      <div class="card my-4">
        <h5 class="card-header">カテゴリー</h5>
        <div class="card-body">
          <div class="row">
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#">アクション</a>
                </li>
                <li>
                  <a href="#">ファンタジー</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <!-- Side Widget -->
      <div class="card my-4">
        <h5 class="card-header">ライター募集</h5>
        <div class="card-body">
          あなたもまとめを投稿してみませんか？<br>mitanoではまとめライターを募集しています。<br>興味がある方はmitanoまでご連絡ください。
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<% set_meta_tags title: @article.title, description: "絶対おすすめ！プリズンブレイクやゲームオブスローンズなど、世界中の海外ドラマを観た編集長が選んだ、2018年、今話題の最高のドラマとは？#{@article.title}", keywords: "海外ドラマ,ランキング,おすすめ,ニュース,ネタバレ,2018",og: { title: "#{@article.title}", type: 'article',description:"絶対おすすめ！プリズンブレイクやゲームオブスローンズなど、世界中の海外ドラマを観た編集長が選んだ、2018年、今話題の最高のドラマとは？#{@article.title}", image: image_url("mitano")} %>


<div class="jumbotron2" style="background-image: url(<%= @article.image%>)">
  <%= render 'partial/navbar' %>
  <div>
    <h1 class="matome-title" color="white"><%= @article.title =%></h1>
  </div>
</div>
<section class="row-space-5">
  <div class="container">

    <div class="col-lg-12 col-xs-12">
      <div class="row" style="padding:10px 0 0 0">
        <%= link_to "HOME", root_path %> >
        <%= link_to "海外ドラマまとめ", articles_path %> >
        <%=link_to "#{@article.title}", article_path(@article) %>
        <div class="box7">
          <p><%= simple_format(@article.heading) %></p>
        </div>
      </div>
    </div>

  </section>
  <% dramaMae = "" %>
  <% count = 1 %>
  <% @articleContents.each do |content|%>

  <% drama = content.drama %>
  <section class="">
    <% if dramaMae != drama%>
    <% count = 1 %>
    <div class="container">
      <div class="col-lg-12 col-xs-12">
        <div class="row" style="padding:10px 0 0 0">
          <h2 class="matome-midasi"><small><%= link_to drama.title, drama_path(drama) %></small></h2>
        </div>
      </div>
      <div class="episode-overview col-md-12 col-xs-12">
        <div class="col-md-4 col-sm-4 portfolio-item box1 center-block text-center">
          <span style="vertical-align:middle;">
            <%= link_to image_tag(drama.image_url), drama_path(drama),:align => 'center'  %>
          </span>
        </div>
        <div class="col-md-8 col-sm-8 portfolio-item">
          <div class="row">
            <div class="col-md-12 col-sm-12">
              <h4 class="episode-summary"><%= drama.over_view %></h4>
              <div class="episode-summary row-space-1">
                <%= link_to "出典：#{drama.source_url}", drama.source_url %>
              </div>
              <div class="episode-summary row-space-1">
                出演：
                <% drama.casts.each do |cast| %>
                <%=link_to(cast.name,cast_path(cast))%>
                <% end %>
              </div>
              <div>
                <%= social_share_button_tag(@article.title) %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% dramaMae = drama %>
    <% end %>
    <div class="container row-space-5">
      <div class="box26">
        <span class="box-title">おすすめポイント<%=count%></span>

        <div class="item2 "><%= content.title %></div>
        <div class="item">
          <p>
            <%= simple_format(content.content) %>
          </p>
        </div>
      </div>
    </div>
  </section>
  <% count += 1 %>
  <% end %>
  <section class="row-space-5">
    <div class="container row-spa">
      <div class="col-lg-12 col-xs-12">
        <div class="row"">
          <div class="item">
            <p><%= simple_format(@article.trailer) %></p>
          </div>
          <%= link_to "HOME", root_path %> >
          <%= link_to "海外ドラマまとめ", articles_path %> >
          <%=link_to "#{@article.title}", article_path(@article) %>
        </div>
      </div>

    </section>

    <div class="container row-space-5">
      <div class="row">
        <div class="box7">
          <p>関連まとめ</p>
        </div>
        <% @articles.each do |article| %>
        <div class="col-md-4 col-sm-6 col-xs-6 portfolio-item  text-center">
          <div class="col-m">
            <div class="card mb-4 box">
              <div class="sp-image">
                <% if request.from_smartphone? %>
                <%= link_to image_tag(article.image,:class =>"sp-image"),article_path(article) %>
                <% else %>
                <%= link_to image_tag(article.image,:size =>"290x150"),article_path(article) %>
                <% end %>
                <div class="card-body">
                  <p class="row-space-1"><%=link_to(article.title,article_path(article))%></p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <br>